# Generated by Django 5.2.12 on 2026-04-28 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteerpreference",
            options={
                "verbose_name": "Volunteer preference",
                "verbose_name_plural": "Volunteer preferences",
            },
        ),
        migrations.AlterField(
            model_name="volunteerpreference",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_preferences",
                to="users.preferencecriterion",
            ),
        ),
    ]
