# Generated by Django 5.2.12 on 2026-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_volunteerpreference_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="block_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="Причина блокування"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата блокування"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="Профіль заблоковано"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="missed_walks_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кількість пропущених прогулянок"
            ),
        ),
    ]
