# Generated by Django 5.2.12 on 2026-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Чоловіча"), ("female", "Жіноча")],
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="animals/photos/"
                    ),
                ),
                ("health_status", models.CharField(blank=True, max_length=255)),
                ("short_description", models.TextField(blank=True)),
                ("favorite_treats", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="animals/qr/"),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
