# Generated by Django 5.2.12 on 2026-04-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Walk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_date", models.DateField()),
                ("planned_start_time", models.TimeField()),
                ("planned_end_time", models.TimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланована"),
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "final_activity_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("unexpected_situations_comment", models.TextField(blank=True)),
                ("character_match_comment", models.TextField(blank=True)),
                (
                    "overall_impression",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks",
                        to="animals.animal",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walks",
                        to="users.volunteerprofile",
                    ),
                ),
            ],
        ),
    ]
