# Generated by Django 5.2.12 on 2026-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walk",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Запланована"),
                    ("active", "Активна"),
                    ("completed", "Завершена"),
                    ("missed", "Пропущена"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
