# Generated by Django 5.2.12 on 2026-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walks", "0002_alter_walk_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="half_hour_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="walk",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
