# Generated by Django 5.2.12 on 2026-05-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walks", "0003_walk_half_hour_reminder_sent_walk_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="completion_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="walk_completion_photos/"
            ),
        ),
    ]
