# Generated by Django 5.2.12 on 2026-05-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat/images/"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
