# Generated by Django 5.2.12 on 2026-04-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorreview",
            name="walk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_reviews",
                to="walks.walk",
            ),
        ),
        migrations.AddField(
            model_name="behaviorreview",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.behaviortrait",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="behaviorreview",
            unique_together={("walk", "trait")},
        ),
    ]
