# Generated by Django 5.2.12 on 2026-04-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
        ("reviews", "0002_initial"),
        ("users", "0002_alter_volunteerpreference_options_and_more"),
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behaviorreview",
            name="comment",
        ),
        migrations.CreateModel(
            name="BehaviorComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_comments",
                        to="animals.animal",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_comments",
                        to="users.volunteerprofile",
                    ),
                ),
                (
                    "walk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_comments",
                        to="walks.walk",
                    ),
                ),
            ],
            options={
                "unique_together": {("walk", "volunteer")},
            },
        ),
    ]
