# Generated by Django 5.2.12 on 2026-04-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
        ("reviews", "0003_remove_behaviorreview_comment_behaviorcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalTraitSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_trait_name", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_suggestions",
                        to="animals.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalSpecificTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_traits",
                        to="animals.animal",
                    ),
                ),
            ],
            options={
                "unique_together": {("animal", "name")},
            },
        ),
    ]
