# Generated by Django 5.2.12 on 2026-04-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
        ("reviews", "0004_animaltraitsuggestion_animalspecifictrait"),
        ("users", "0002_alter_volunteerpreference_options_and_more"),
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalSpecificTraitReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_trait_reviews",
                        to="animals.animal",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.animalspecifictrait",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_trait_reviews",
                        to="users.volunteerprofile",
                    ),
                ),
                (
                    "walk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specific_trait_reviews",
                        to="walks.walk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Animal specific trait review",
                "verbose_name_plural": "Animal specific trait reviews",
                "unique_together": {("walk", "volunteer", "trait")},
            },
        ),
    ]
