# Generated by Django 5.2.12 on 2026-05-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
        ("notifications", "0001_initial"),
        ("users", "0003_volunteerprofile_block_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walks_count", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_recommendations",
                        to="animals.animal",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_recommendations",
                        to="users.volunteerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("volunteer", "animal")},
            },
        ),
    ]
